// No-WebGL / no-glb fallback: the Blender side elevation render (public/r151_elevation.png,
// 4000 x 198 for the 8-car set, orthographic) with an SVG health marker per component on top.
//
// The marker coordinates in elevationMarkers.json are generated by assets3d/fit_markers.py from
// the pure-python part layout of build_r151.py and the linear fit of the render
//     x_px = a + b * x_world      y_px = c - b * y_world
// re-derived by least squares from the inter-car body edges and the rail top measured in the PNG
// (the fitted a, b, c are stored in the file under "fit"). Everything about the set - the number
// of cars, the image size, which components exist - is read from that file, nothing is assumed.
//
// Same inputs as TrainViewport: a replay `frame` + `trainId`, or a PS3 `healthMap` that wins.
import React from "react";
import MARKERS from "./elevationMarkers.json";
import {
  componentKey,
  HEALTH_COLORS,
  HEALTH_WORDS,
  indexFrame,
  indexHealthMap,
  statsLine,
} from "./componentMap.js";
import { C, fmtScore } from "../../lib/format.js";
import "./viewport.css";

export const CARS = Object.keys(MARKERS.cars).sort((a, b) => +a - +b);

/** Header counts from the markers file (the 3D view computes the same from the glb). */
export const MARKER_STATS = {
  cars: CARS.length,
  doors: CARS.reduce((n, c) => n + Object.keys(MARKERS.cars[c].doors ?? {}).length, 0),
  bogies: CARS.reduce((n, c) => n + Object.keys(MARKERS.cars[c].bogies ?? {}).length, 0),
  axleboxes: CARS.reduce((n, c) => n + Object.keys(MARKERS.cars[c].axleboxes ?? {}).length, 0),
  ac: CARS.reduce((n, c) => n + (MARKERS.cars[c].ac ? 1 : 0), 0),
};

function Marker({ box, health, selected, pickable, onPick, title }) {
  const fill = health === "nodata" ? "none" : HEALTH_COLORS[health];
  const stroke = selected ? C.accent : health === "nodata" ? C.line2 : HEALTH_COLORS[health];
  return (
    <g
      className={pickable ? "nx-hit" : undefined}
      onClick={pickable ? onPick : undefined}
      role={pickable ? "button" : undefined}
      tabIndex={-1}
      aria-label={title}
    >
      <title>{title}</title>
      <rect
        x={box.x}
        y={box.y}
        width={box.w}
        height={box.h}
        fill={fill}
        fillOpacity={health === "crit" ? 0.95 : health === "nodata" ? 0 : 0.85}
        stroke={stroke}
        strokeWidth={selected ? 3 : 1}
      >
        {health === "crit" ? (
          <animate attributeName="fill-opacity" values="0.95;0.35;0.95" dur="1.8s" repeatCount="indefinite" />
        ) : null}
      </rect>
    </g>
  );
}

export default function TrainElevationFallback({
  frame,
  trainId,
  selected,
  onSelect,
  height = 206,
  reason = "",
  healthMap = null,
  overlay = null,
  captions = null,
  viewMode = null,
}) {
  const mapMode = !!healthMap;
  const train = mapMode
    ? null
    : (frame?.trains?.find((t) => t.train_id === trainId) ?? frame?.trains?.[0] ?? null);
  const byKey = overlay || (mapMode ? indexHealthMap(healthMap) : indexFrame(train));
  const id = mapMode ? (trainId ?? "PS3") : (train?.train_id ?? trainId ?? "-");
  const selKey = selected
    ? componentKey(selected.car, selected.subsystem, selected.component_id)
    : null;
  const title = mapMode ? (healthMap.caption ?? "PS3 PREDICTION") : `SET ${id}`;
  const focusCar = viewMode === "pneumatic" ? 3 : ["door", "shm", "bearing"].includes(viewMode) ? 1 : null;
  const body = focusCar ? MARKERS.cars[String(focusCar)]?.body : null;
  const cropWidth = 530;
  const viewBox = body
    ? `${body.x + body.w / 2 - cropWidth / 2} 35 ${cropWidth} 105`
    : `0 0 ${MARKERS.width} ${MARKERS.height}`;
  const counts = { crit: 0, warn: 0 };
  for (const v of byKey.values()) if (counts[v.health] != null) counts[v.health] += 1;

  const pick = (car, subsystem, component_id) => () => {
    const comp = byKey.get(componentKey(car, subsystem, component_id));
    onSelect?.({
      train_id: id,
      car: comp && comp.car != null ? comp.car : car,
      subsystem,
      component_id,
    });
  };

  // one marker per box; a component may own several boxes (the two roof AC units of a car)
  const markerFor = (car, subsystem, component_id, box, hint = "") => {
    const key = componentKey(car, subsystem, component_id);
    const comp = byKey.get(key);
    const health = comp?.health ?? "nodata";
    const score =
      comp && comp.score != null ? ` · ${fmtScore(+comp.score)}/${fmtScore(+comp.threshold)}` : "";
    const label = comp?.label ? ` · ${comp.label}` : "";
    const pickable = comp != null;
    const where = subsystem === "rail" ? `rail ${component_id.slice(5)}` : `car ${car} · ${component_id}`;
    return (
      <Marker
        key={`${key}@${box.x},${box.y}`}
        box={box}
        health={health}
        selected={selKey === key}
        pickable={pickable}
        onPick={pick(car, subsystem, component_id)}
        title={`${where}${hint} · ${HEALTH_WORDS[health]}${score}${label}`}
      />
    );
  };

  return (
    <div className="nx-vp" style={{ height }}>
      <div className="nx-vp-head">
        <div className="nx-vp-title">
          <b>{title} &middot; {viewMode === "rail" ? "TOP VIEW" : "SIDE ELEVATION"}</b>
          <span>
            {statsLine(MARKER_STATS)}
            {counts.crit || counts.warn ? ` · ${counts.crit} alert / ${counts.warn} watch` : ""}
          </span>
        </div>
        <div className="nx-vp-legend">
          <div><i style={{ background: HEALTH_COLORS.ok }} />OK</div>
          <div><i style={{ background: HEALTH_COLORS.warn }} />WATCH</div>
          <div><i style={{ background: HEALTH_COLORS.crit }} />ALERT</div>
          {viewMode !== "rail" && <div><i style={{ background: C.line2 }} />FAR SIDE R1&ndash;R4</div>}
        </div>
      </div>
      <div className="nx-vp-fallback">
        {viewMode === "rail" ? (
          <svg className="nx-rail-fallback" viewBox="0 0 1000 160" role="img" aria-label="Top view of the two rail sides beneath an eight-car train">
            {Array.from({ length: 8 }, (_, i) => <rect key={i} x={38 + i * 116} y="35" width="108" height="90" rx="8" fill="#e4ecef" stroke="#c8d6dd" />)}
            {[["II", 55], ["I", 105]].map(([side, y]) => {
              const cid = `rail_${side}`;
              const comp = byKey.get(componentKey(0, "rail", cid));
              const h = comp?.health || "nodata";
              const isSelected = selKey === componentKey(0, "rail", cid);
              return <g key={side} onClick={comp ? pick(0, "rail", cid) : undefined} style={{ cursor: comp ? "pointer" : "default" }}>
                <line x1="20" y1={y} x2="980" y2={y} stroke={h === "nodata" ? C.line2 : HEALTH_COLORS[h]} strokeWidth={isSelected ? 14 : 10} />
                <text x="35" y={y - 11} fill={C.text} fontSize="15" fontWeight="700">SIDE {side}</text>
              </g>;
            })}
          </svg>
        ) : <div className="nx-vp-fallback-inner">
          <svg viewBox={viewBox} preserveAspectRatio="xMidYMid meet" role="img" aria-label={`Side elevation of ${title.toLowerCase()}`}>
            <image href={MARKERS.image} x="0" y="0" width={MARKERS.width} height={MARKERS.height} />
            {MARKERS.rails
              ? Object.entries(MARKERS.rails).map(([cid, box]) => markerFor(0, "rail", cid, box))
              : null}
            {CARS.map((car) => {
              const c = MARKERS.cars[car];
              if (!c) return null;
              const n = +car;
              return (
                <g key={car}>
                  {Object.entries(c.doors ?? {}).map(([cid, box]) => markerFor(n, "door", cid, box))}
                  {Object.entries(c.axleboxes ?? {}).map(([cid, box]) => markerFor(n, "bearing", cid, box))}
                  {Object.entries(c.bogies ?? {}).map(([cid, box]) => markerFor(n, "shm", cid, box))}
                  {c.apu ? markerFor(n, "pneumatic", "apu_1", c.apu) : null}
                  {c.ac
                    ? Object.entries(c.ac).map(([unit, box]) => markerFor(n, "acv", "ac_1", box, ` (${unit})`))
                    : null}
                  <text
                    x={c.label.x}
                    y={c.label.y}
                    textAnchor="middle"
                    fontFamily="'IBM Plex Mono', monospace"
                    fontSize="22"
                    fontWeight="600"
                    fill="#828d9e"
                  >
                    CAR {car}
                  </text>
                </g>
              );
            })}
          </svg>
        </div>}
        {captions && captions.length > 0 ? (
          <div
            className="nx-vp-captions"
            style={{
              position: "absolute",
              left: 10,
              bottom: 4,
              display: "flex",
              flexDirection: "column",
              gap: 2,
              zIndex: 10,
              pointerEvents: "none",
            }}
          >
            {captions.map((cap, i) => (
              <div
                key={i}
                className="mono"
                style={{
                  fontSize: 9.5,
                  letterSpacing: "0.06em",
                  color: C.accent,
                  background: "rgba(255, 255, 255, 0.92)",
                  padding: "1px 6px",
                  borderLeft: `2px solid ${C.accent}`,
                }}
              >
                {cap}
              </div>
            ))}
          </div>
        ) : null}
        <div className="nx-vp-note">2D fallback{reason ? ` · ${reason}` : ""}</div>
      </div>
    </div>
  );
}
